POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "gestionnaire",
  "password": "gestionnaire123"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "caissier",
  "password": "caissier123"
}