spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/gestion_commerciale
spring.datasource.username=postgres
spring.datasource.password=050598

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Serveur
server.port=8080

# Actuator : expose /actuator/health comme vérification d'état de l'application
management.endpoint.health.show-details=always